apiVersion: v2
name: helmet
description: Helmet is a library Helm Chart for grouping common logics. This chart is not deployable by itself.
home: https://github.com/companyinfo/helm-charts/blob/main/charts/helmet
type: library
version: "0.6.5"
appVersion: "0.6.5"
keywords:
  - common
  - helper
  - template
  - function
maintainers:
  - name: Company.info Developers
    url: https://company.info
dependencies:
  - name: common
    version: "2.2.2"
    repository: "https://charts.bitnami.com/bitnami"
